### PR TITLE
Set native module function on index

### PR DESCRIPTION
**Pull request by originerd**
- Set setupPush function for ios
- Add clearAllNotifications function for android to index

### CODE REVIEW

**Comment by KenChoi1992** [comment]
Thanks for committing pull request, we will deal with it soon.

**Comment by huangminlinux** [comment]
这个方法还没有适配 iOS10

**Comment by originerd** [comment]
@huangminlinux It needs to add to [`AppDelegate.m`](https://github.com/jpush/jpush-react-native/blob/master/README.md#ios-usage)
```
[JPUSHService setupWithOption:launchOptions appKey:appKey
              channel:channel apsForProduction:isProduction];
```

I checked it on iOS 10.

**Comment by huangminlinux** [comment]
So this situation a little embarrassed. we have to add the code in AppDelegate.m and js. 
   
In later versions，I will using a more elegant method to  implement it.

**Pull request merged**
